jwt:
  header: Authorization
  secret: aaaaaaaaaaaaaaaaabbbbbbbbbbbbbbbbbbbbbbbccccccccccc
  tokenValidityInSeconds: 8640000
spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
spring-doc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/**