name: Java CI with Gradle

# 변경 감지할 브랜치
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

# 실행 내용
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. 깃허브 코드 가져오기
      - uses: actions/checkout@v3

      # 2. JDK 환경 세팅
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. properties 생성
      - name: make application-prod.yml
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.YML_PROD }}" > ./application-prod.yml

      # 4. gradle 통해 자바 소스 빌드
      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew clean build -x test

      # 5. 도커에 이미지 업로드 (로그인, 이미지 빌드, 푸쉬)
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -f Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/albbaim .
          docker push ${{ secrets.DOCKER_USERNAME }}/albbaim
      
      # 6. 도커 이미지 pull, 실행
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        id: deploy
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/albbaim
            sudo docker stop $(docker ps -qa)
            sudo docker run -d -p 8080:8080 ${{ secrets.DOCKER_USERNAME }}/albbaim
            sudo docker rm $(docker ps --filter 'status=exited' -a -q)
            sudo docker image prune -a -f
